# Generated by Django 4.2.1 on 2023-05-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='lable',
            new_name='label',
        ),
    ]
